language: node_js

cache:
  npm: true
  directories:
    - node_modules

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - echo "@testing" > server/.arc-env
  - echo "PASSWORD letmein" >> server/.arc-env
