#!/usr/bin/env bash

set -e

npm test
npm run build

cp _headers build/_headers
echo -e "\n/*
  X-Robots-Tag: noindex, noarchive
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Referrer-Policy: same-origin
  Basic-Auth: $USER:$PASS" >> build/_headers
