name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Create AWS credentials file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          echo "[ek-photo-upload]" > ~/.aws/credentials
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      - name: Build, test & deploy the application
        env:
          PASSWORD: letmein
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          TLD: ${{ secrets.TLD }}
        run: |
          npm install
          npm test
          make deploy-prod

      - name: Remove credentials file
        run: rm -f ~/.aws/credentials
