name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: actions/checkout@v1
    - name: Build & test the application
      run: |
        npm install
        npm test
